name: Generate OIDC Token

on:
  workflow_dispatch:

jobs:
  get-oidc-token:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Request GitHub OIDC Token
        id: oidc
        run: |
          TOKEN=$(curl -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
                      "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=github-wif")
          echo "$TOKEN" > github-oidc-token.json
          cat github-oidc-token.json
      - name: Extract JWT
        run: jq -r '.value' github-oidc-token.json > github-oidc-token.jwt
      - name: Upload JWT artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-oidc-token
          path: github-oidc-token.jwt
